// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA39TCezYwH3ov68oVONo81BDoicbSK5sU',
    appId: '1:771785756007:web:1b81d823c86c69a6d2f3c2',
    messagingSenderId: '771785756007',
    projectId: 'myfirstapp-8e604',
    authDomain: 'myfirstapp-8e604.firebaseapp.com',
    storageBucket: 'myfirstapp-8e604.appspot.com',
    measurementId: 'G-9WXMFR0TB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBZQD23DjL0IAUaotVAzomNBIsfUrdMRI',
    appId: '1:771785756007:android:039878cd727e7649d2f3c2',
    messagingSenderId: '771785756007',
    projectId: 'myfirstapp-8e604',
    storageBucket: 'myfirstapp-8e604.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzJW3st1AZTnVlJF4OfO_o0Mecsjud4qo',
    appId: '1:771785756007:ios:7c150ab10e0748f6d2f3c2',
    messagingSenderId: '771785756007',
    projectId: 'myfirstapp-8e604',
    storageBucket: 'myfirstapp-8e604.appspot.com',
    iosClientId: '771785756007-qfbj1t29ro8tc1mlif0aufbdmo3i8nhm.apps.googleusercontent.com',
    iosBundleId: 'com.example.julyBatchFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzJW3st1AZTnVlJF4OfO_o0Mecsjud4qo',
    appId: '1:771785756007:ios:0315ca04627bcb7fd2f3c2',
    messagingSenderId: '771785756007',
    projectId: 'myfirstapp-8e604',
    storageBucket: 'myfirstapp-8e604.appspot.com',
    iosClientId: '771785756007-6hjl7u310rj223ik657l1girrvrl8qu0.apps.googleusercontent.com',
    iosBundleId: 'com.example.julyBatchFlutter.RunnerTests',
  );
}
